apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd_blue_green_demo
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd_blue_green_demo
  template:
    metadata:
      labels:
        app: argocd_blue_green_demo
    spec:
      containers:
      - name: argocd_blue_green_demo
        image: joelwembo/argocd_blue_green_demo:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: argocd_blue_green_demo_service
  namespace: argocd
spec:
  type: LoadBalancer
  selector:
    app: argocd_blue_green_demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
